### ISSUE TITLE
Lack of error handling in stream.read

### ISSUE THREAD

**Issue by staltz** [ssb-js/muxrpc#50]
Related to ssb-tunnel, I got this error:

```
/root/ssb-room/node_modules/muxrpc/stream.js:57
        var name = data.name
                        ^

TypeError: Cannot read property 'name' of null
    at PacketStreamSubstream.stream.read (/root/ssb-room/node_modules/muxrpc/stream.js:57:25)
    at PacketStream._onstream (/root/ssb-room/node_modules/packet-stream/index.js:224:13)
    at PacketStream.write (/root/ssb-room/node_modules/packet-stream/index.js:135:41)
    at /root/ssb-room/node_modules/muxrpc/pull-weird.js:56:15
    at /root/ssb-room/node_modules/pull-stream/sinks/drain.js:24:37
    at /root/ssb-room/node_modules/pull-goodbye/node_modules/pull-stream/throughs/filter.js:17:11
    at Object.cb (/root/ssb-room/node_modules/packet-stream-codec/index.js:111:11)
    at drain (/root/ssb-room/node_modules/pull-reader/index.js:39:14)
    at more (/root/ssb-room/node_modules/pull-reader/index.js:55:13)
    at /root/ssb-room/node_modules/pull-reader/index.js:66:9
```

It's at this line: https://github.com/ssbc/muxrpc/blob/210fac6827b5192a62599401acb55a9e78da0542/stream.js#L56-L67

I think the `end` case should be checked before using `data`, but the first line assumes that `data` exists. I think the error handling hasn't felt 'necessary' so far, but ssb-tunnel is unconventional enough that it might hit more corner cases.

**Comment by Happy0** [comment]
@staltz - it's funny that we both ran into this edge case in the same week ( https://github.com/ssbc/muxrpc/issues/49 )

**Comment by staltz** [comment]
Stop it, bot

**Comment by dominictarr** [comment]
hmm, why would this be happening? normally the outer stream will be the one that has the unexpected error. can anyone make (or at least describe) how to hit this edge case?
